<?xml version="1.0"?>

<robot name="snake" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
	<!-- snake properties -->
	<xacro:property name="num_links" value ="5" />
	<xacro:property name="link_length" value="0.5" />
	<xacro:property name="link_radius" value="0.025" />
	<xacro:property name="link_mass" value="0.2" />
	<xacro:property name="joint_friction" value="0.2" />
	<xacro:property name="joint_damping" value="0.001" />
	<xacro:property name="spring_mass" value="0.001" />
	<xacro:property name="spring_inertia" value="0.0" />
	<xacro:property name="pi" value="3.1415" />
	<xacro:property name="joint_type" value="1" /> <!-- 1=simple_joint -1=springy_joint -->

	<xacro:macro name="snake_link" params="number">
		<link name="module_${number}">
			<collision>
				<geometry>
					<cylinder length="${link_length}" radius="${link_radius}" />
				</geometry>
				<origin xyz="0 0 -${link_length/2}" rpy="0 0 0" />
			</collision>

			<visual>
				<geometry>
					<cylinder length="${link_length}" radius="${link_radius}" />
				</geometry>
				<origin xyz="0 0 -${link_length/2}" rpy="0 0 0" />
			</visual>

			<inertial>
				<origin xyz="0 0 -${link_length/2}" rpy="0 0 0" />
				<mass value="0.159" />
				<inertia ixx="0.00006" iyy="0.00006" izz="0.00006" ixy="0" ixz="0" iyz="0" />
			</inertial>
		</link>   
	</xacro:macro>

	<xacro:macro name="snake_joint" params="parent child axis">
		<xacro:if value="${-joint_type-1}">
			<xacro:simple_joint parent="${parent}" child="${child}" axis="${axis}"/>
		</xacro:if>
		<xacro:if value="${joint_type-1}">
			<xacro:spring_joint parent="${parent}" child="${child}" axis="${axis}"/>
		</xacro:if>
	</xacro:macro>
	
	<!-- Spring joints are joints with a center springy link-->
	<xacro:macro name="spring_joint" params="parent child axis">
		<!-- Springy joint -->
		<joint name="joint_${parent}_m" type="revolute">
			<limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}"
				velocity="10" />
			<dynamics damping="${joint_damping}" friction="${joint_friction}" />
			<parent link="module_${parent}" />
			<child link="spring_${parent}" />
			<origin xyz="0 0 -${link_length}" />
			<axis xyz="${axis}" />
		</joint>
		<link name="spring_${parent}">
			<visual>
				<geometry>
					<cylinder length="${2*link_radius}" radius=".001" />
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
			</visual>
			<inertial>
				<mass value="${spring_mass}" />
				<inertia ixx="${spring_inertia}" ixy="0.0" ixz="0.0"
					iyy="${spring_inertia}" iyz="0.0" izz="${spring_inertia}" />
			</inertial>
		</link>
		<joint name="joint_${parent}_${child}" type="revolute">
			<limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}"
				velocity="10" />
			<!-- <dynamics damping="${damping}" friction="${friction}" /> -->
			<parent link="spring_${parent}" />
			<child link="module_${child}" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<axis xyz="${axis}" />
		</joint>
	</xacro:macro>
	
	<!-- Simple joints are simple, lightly damped and frictioned joints-->
	<xacro:macro name="simple_joint" params="parent child axis">
		<!-- Simple joint -->
		<joint name="joint_${parent}_${child}" type="revolute">
			<limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}"
				velocity="10" />
			<dynamics damping="${joint_damping}" friction="${joint_friction}" />
			<parent link="module_${parent}" />
			<child link="module_${child}" />
			<origin xyz="0 0 -${link_length}" />
			<axis xyz="${axis}" />
		</joint>
	</xacro:macro>
	
	<xacro:macro name="snake_tail" params="links_qty flip_axis">
		<xacro:if value="${flip_axis}">
					<xacro:snake_joint parent="${links_qty}" child="${links_qty-1}" axis="1 0 0" />
		</xacro:if>
		<xacro:if value="${1-flip_axis}">
					<xacro:snake_joint parent="${links_qty}" child="${links_qty-1}" axis="0 1 0" />
		</xacro:if>
		<xacro:snake_link number="${links_qty-1}" />
		<xacro:if value="${links_qty}">
			<xacro:snake_tail links_qty="${links_qty-1}" flip_axis="${1-flip_axis}" />
		</xacro:if>
	</xacro:macro>

	<xacro:macro name="snake" params="links_qty">
		<xacro:snake_link number="${links_qty}" />
		<xacro:snake_tail links_qty="${links_qty}" flip_axis="0"/>
	</xacro:macro>
	
	<xacro:snake links_qty="${num_links}" />
</robot>
